server:
  port: 8088

#db:
#  host:
#  port:
#  name:
#  username:
#  password:

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /docs

spring:
  jpa:
    open-in-view: off
  hibernate:
    ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  datasource:
    url: ${DB_HOST}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000
      minimum-idle: 50
      maximum-pool-size: 500
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    group-id: ${SPRING_KAFKA_GROUP_ID}
    topics:
      user-attendance: user_attendance
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.scheduler:
        instanceName: Scheduler
        instanceId: AUTO
        makeSchedulerThreadDaemon: true
      org.quartz.jobStore:
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        dataSource: dataSource
        tablePrefix: QRTZ_
      org.quartz.threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        makeThreadsDaemons: true
        threadCount: 20
        threadPriority: 5
      org.quartz.dataSource:
        dataSource:
          driver: com.mysql.cj.jdbc.Driver
          URL: ${DB_HOST}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
          user: ${DB_USERNAME}
          password: ${DB_PASSWORD}
          maxConnections: 20
  redis:
    host: ${REDIS_HOST:localhost} # Default to 'localhost' if not provided
    port: ${REDIS_PORT:6379}
#  redis:
#    sentinel:
#      master: redis-cluster               # Tên của Redis master set
#      nodes: localhost:26379              # Địa chỉ của Sentinel
#    password: springboot

logging:
  level:
    org.springframework.scheduling.quartz: DEBUG
    org.quartz: DEBUG
    org.springframework.boot: DEBUG
