server:
  port: 8088

#db:
#  host:
#  port:
#  name:
#  username:
#  password:

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /docs

elasticsearch:
  url: localhost:9200


spring:
  jpa:
    open-in-view: off
  hibernate:
    ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  datasource:
    url: ${DB_HOST}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000
      minimum-idle: 50
      maximum-pool-size: 500
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    group-id: ${SPRING_KAFKA_GROUP_ID}
    topics:
      user-attendance: user_attendance
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.scheduler:
        instanceName: Scheduler
        instanceId: AUTO
        makeSchedulerThreadDaemon: true
      org.quartz.jobStore:
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        dataSource: dataSource
        tablePrefix: QRTZ_
      org.quartz.threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        makeThreadsDaemons: true
        threadCount: 20
        threadPriority: 5
      org.quartz.dataSource:
        dataSource:
          driver: com.mysql.cj.jdbc.Driver
          URL: ${DB_HOST}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
          user: ${DB_USERNAME}
          password: ${DB_PASSWORD}
          maxConnections: 20
  redis:
    host: ${REDIS_HOST:localhost} # Default to 'localhost' if not provided
    port: ${REDIS_PORT:6379}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 634024087696-fkj2i38lh8doloo12vokb70fisn0qif0.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "${GOOGLE_REDIRECT_URI:http://localhost:4300/auth/google/callback}" #sau khi user đăng nhập google thành công sẽ tự redirect đến trang này kèm code(của gooogle)
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            #auth-uri: "https://www.facebook.com/v3.2/dialog/oauth"
            resource-server:
              opaque-token:
                introspection-uri: "https://googleapis.com"  # Đảm bảo URI này chính xác
          facebook:
            client-id: 1007654770988152
            client-secret: 5adb1d315754ac7e7e26b09d4c8b8b17
            redirect-uri: "${GOOGLE_REDIRECT_URI:http://localhost:4300/auth/facebook/callback}" #sau khi user đăng nhập google thành công sẽ tự redirect đến trang này kèm code(của fb)
            auth-uri: https://www.facebook.com/v21.0/dialog/oauth
            token-uri: https://graph.facebook.com/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)
            scope:
              - email
              - public_profile

#  redis:
#    sentinel:
#      master: redis-cluster               # Tên của Redis master set
#      nodes: localhost:26379              # Địa chỉ của Sentinel
#    password: springboot

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=


logging:
  level:
    org.springframework.scheduling.quartz: DEBUG
    org.quartz: DEBUG
    org.springframework.boot: DEBUG
